// File generated by FlutterFire CLI.
// Run `flutterfire configure` with your Firebase project to replace the
// placeholder values below with real credentials, or manually copy the values
// from your Firebase console (Project Settings > Your apps).
//
// TODO: Replace all placeholder values with your actual Firebase credentials.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace with your Firebase web app credentials.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnfcp89CBYnn0e-iMpx-bcVLLSeRDl-PQ',
    appId: '1:1093787683868:web:cbfb38400d174042e963d9',
    messagingSenderId: '1093787683868',
    projectId: 'flixie-9a8eb',
    authDomain: 'flixie-9a8eb.firebaseapp.com',
    storageBucket: 'flixie-9a8eb.appspot.com',
  );

  // TODO: Replace with your Firebase Android app credentials.
  // These values come from your google-services.json file.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoDU1xEPxVJ-hCr41gc1QIGTKjjQeRTgo',
    appId: '1:1093787683868:android:ba7f4704c76d4e65e963d9',
    messagingSenderId: '1093787683868',
    projectId: 'flixie-9a8eb',
    storageBucket: 'flixie-9a8eb.appspot.com',
  );

  // TODO: Replace with your Firebase iOS app credentials.
  // These values come from your GoogleService-Info.plist file.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEgK7FOpbLfLCdXsDGtETv9ciPgCcdFQQ',
    appId: '1:1093787683868:ios:a13967c2215d82f3e963d9',
    messagingSenderId: '1093787683868',
    projectId: 'flixie-9a8eb',
    storageBucket: 'flixie-9a8eb.appspot.com',
    iosClientId: '1093787683868-0vo57s3c7hud798645h5cjc11i5jt43v.apps.googleusercontent.com',
    iosBundleId: 'com.flixie.flixieApp',
  );
}
